### ISSUE TITLE
napariで軸を変えてみた時のポイントを表示してほしい

### ISSUE THREAD

**Issue by nakamura-koki** [neurobiology-ut/napari_app#22]
napariでミスアノテーションしているものを他の面で見たい！と思った時に、xy面からyz面に移行すると、さっき見ていたポイントがどこかわからなくなっちゃいます。
xy平面で注目している領域を色塗りすると、yz平面でも zx平面でも見えるようにしてもらえると助かります。

**Comment by Shogosuga** [comment]
point layerで一つだけ点を打つと、その点を含む面をyz, zx面でも別layerで表示させる、みたいな感じでしょうか？

**Comment by nakamura-koki** [comment]
そういうことです！

**Comment by hiroalchem** [comment]
こういうことですか？
![](https://research.stowers.org/imagejplugins/images/imagej_tutorial/image030.png)

**Comment by hiroalchem** [comment]
orthogonal view

**Comment by nakamura-koki** [comment]
はい！それが見えると嬉しいです！

**Comment by hiroalchem** [comment]
https://github.com/napari/napari/issues/1478
公式に検討中のようですが、まだ少しかかりますね
一時的に表示するだけなら難しくないですが、連動させたりするのは少しトリッキーと思われます
検討します

**Comment by nakamura-koki** [comment]
個人的には、連動しなくてもスナップショット的に見れれば十分だと思っています。
検討よろしくお願いします

**Comment by Shogosuga** [comment]
スナップ的なのであれば作れそうなので、ちょっと作ってみます

**Comment by hiroalchem** [comment]
https://twitter.com/jnuneziglesias/status/1286599143008346112
これが参考になります

**Comment by Shogosuga** [comment]
ありがとうございます
参考にします

**Comment by hiroalchem** [comment]
実装済みなのでcloseします
