### ISSUE TITLE
クリステのtube/ラメラの比率

### ISSUE THREAD

**Issue by Shogosuga** [neurobiology-ut/napari_app#30]

**Comment by Shogosuga** [comment]
@nakamura-koki @yh-hgkr 
足りない箇所があれば付け加えてください

lamellarとtubularの判別方法について
・色が違う（lamellarだと膜が重なって見えるため、かなり黒く見えている）
・長さが違う（平面上で長かったら？）

この二軸で考え、これらのパラメータから判別つかないものは「どちらかわからない構造体」とする。

**Comment by yh-hgkr** [comment]
今の解像度の場合、中が空洞の構造が見られたら、tubularと定義してもほぼ安全な気がします。

**Comment by hiroalchem** [comment]
すいません、確認なんですが、tubularとlamellarについては独立ではなくて、それぞれ繋がっていて、コンパートメント単位でtubularかlamellarかに分かれているという感じでしょうか。
「どちらかわからない構造体」というのは、「どちらでもない中間的なコンパートメント」である場所もある、という理解で合っていますか。

**Comment by Shogosuga** [comment]
曖昧な記述で申し訳ありません。

>tubularとlamellarについては独立ではなくて、それぞれ繋がっていて、コンパートメント単位でtubularかlamellarかに分かれているという感じでしょうか。
はい。tubularは独立しているものも見受けられますが、基本的にはlamellarと繋がっています。

> 「どちらかわからない構造体」というのは、「どちらでもない中間的なコンパートメント」である場所もある、という理解で合っていますか。
はい。合っています。

**Comment by hiroalchem** [comment]
ありがとうございます。
だいたい追いついた気がします。
先日話していたクラスタリングの話しだと、領域単位で考える必要があるでしょうか。
https://www.riken.jp/press/2020/20200203_1/index.html
これはちょっと違う例ですが、こういった手法をsubvoxelに分割したクリステに対して行うという方法もあり得ます。

**Comment by Shogosuga** [comment]
![cropped_001_cristae_hist](https://user-images.githubusercontent.com/43239176/89153786-933db580-d5a0-11ea-8cee-692cef008dc4.jpg)

cropped_001のクリステのヒストグラムです。x軸の０がblackで255がwhiteを示してます。white寄りのピクセルはおそらくlamellarの外側の一部あるいはtubelarであると思います。どこかの値でthreshとるかはこれから試してみます。

**Comment by Shogosuga** [comment]
こちらもcloseします。
