### ISSUE TITLE
feature/confirm_at_other_axes

### ISSUE THREAD

**Issue by Shogosuga** [neurobiology-ut/napari_app#35]
https://github.com/neurobiology-ut/napari_app/issues/22
についてです。

**Comment by Shogosuga** [comment]
■実装方法
・label layerに加えて、point layerを表示（初期値なし）
↓
・ユーザーがpoint layerで点を打つ
↓
・その点を含む他軸方面の画像を別のlayerに出す

**Comment by hiroalchem** [comment]
point layerなしで、keybindingsとmousefunction？でできますか？僕の書いたcropのコードを参考に

**Comment by Shogosuga** [comment]
やってみます

**Comment by Shogosuga** [comment]
■実装方法
・label layerを表示
↓
・ユーザーがoriginal layerで点を打つ
↓
・その点を含む他軸方面の画像を別のlayerに出す

**Comment by hiroalchem** [comment]
https://gist.github.com/jni/a0ae9793a0ca43868dd7dce7ea21df79
また、
viewer.window.add_dock_widget(mz_canvas)
でmatplotlibで作成した図をはりつけられることから、画像も貼り付けられると思うので画像の下や右に出すことも余裕があったら検討しても良いかなと思います。
余裕があったらで良いです。

**Comment by hiroalchem** [comment]
マウスクリックにfunctionをつけるのは
https://github.com/neurobiology-ut/napari_app/blob/develop/napari_view.py#L55
ここでやっています
また
https://github.com/neurobiology-ut/napari_app/blob/develop/napari_view.py#L49
add_dock_widgetで貼り付ける場所は指定ができます。(この例だとbottom、'left', 'right', 'top', 'bottom'が指定可能)

**Comment by hiroalchem** [comment]
実装済みなのでcloseします
