### ISSUE TITLE
predictionの数値が中間のpixelが多いsliceまたはpixelの塊ごとにアラートを出す機能

### ISSUE THREAD

**Issue by hiroalchem** [neurobiology-ut/napari_app#44]

**Comment by Shogosuga** [comment]
こちらActive Learningのために着手します！

**Comment by hiroalchem** [comment]
ありがとうございます！
修正済みスライスorピクセルと推論結果の値の相関って取れてるんでしたっけ！？

**Comment by Shogosuga** [comment]
忘れてましたので、今から調査します！

**Comment by Shogosuga** [comment]
![スクリーンショット 2021-02-15 19 52 28](https://user-images.githubusercontent.com/43239176/107937497-5890ed00-6fc7-11eb-9d17-e750fa82b3e6.png)


@hiroalchem @yh-hgkr @nakamura-koki 

こちら、ミトコンドリアのセグメンテーションで、修正対象となっているピクセルと平均した推論値の相関をグラフにしたものです。
横軸がピクセルの値、縦軸がピクセルの数を表しています。

このグラフ内にはピークが2つあり、一つは255（三方向全て誤って推論してしまっている）、もう一つは170（三方向中二方向のみ誤って推論している）のものでした。

なので、推論値が127~170のピクセルが多いスライスにアラートを出すようにしたいです。

**Comment by hiroalchem** [comment]
3方向全て間違えているパターンがどういうものか確認していただくこと可能ですか？？

**Comment by hiroalchem** [comment]
説明不十分でした。修正したピクセルのブロック単位で見た時、171〜255のピクセルしか含まれていない(もしくは170以下がごく一部しか含まれていない)率です
また、これだとほぼ余計に塗られていてそれを消したというパターンしかないようですが、それであってます？？

**Comment by Shogosuga** [comment]
> これだとほぼ余計に塗られていてそれを消したというパターンしかないようですが、それであってます？？
いえ、ミトコンであると正しく推論できていない（推論値が127未満）のピクセルが存在しています。

**Comment by Shogosuga** [comment]
![スクリーンショット 2021-02-15 21 24 20](https://user-images.githubusercontent.com/43239176/107946303-2fc32480-6fd4-11eb-8980-191cf0a93cba.png)

三方向全てにおいて間違えて”ミトコンである”と推論していた大半の部分は、図のようにlysosomeなどの別のオルガネラでした。
（赤：修正後のミトコン、緑：ミトコンだと推論された箇所、黄：左の2つの重複部分）

**Comment by hiroalchem** [comment]
次のような実装であれば1日あればできると思いますが、いかがでしょうか？
・推論結果の2値化前の値の画像をxxx_rawというディレクトリに置く
・値が127~170のピクセルを255それ以外を0とする (またはさらに何らかの処理をかけた画像、今はmedianフィルター処理を想定) 
・その画像をnapariに追加layerとして表示する (low confidence layer)

また、間違えて”ミトコンである”と推論していた部分は概ねlysosomeなど別のオルガネラとのことですが、おそらくサイズが小さいので
・各ミトコンドリアにlabelを与えてそのvolumeが閾値以下のlabelを抜き出す
・そのlabelの領域もnapariに追加チャネルとして表示する (small volume layer)
でいかがでしょうか？

両方とも本当はpixel数をスライダー等で閾値を設定できるようにしたいのですが、今の所はスピードを重視して決め打ちします。
よければ明日〜明後日の間に実装します。後者のvolumeとしては10万pixelを想定していますがいかがでしょうか？間違って推論されているオルガネラのvolume(pixels)は10万以下でしょうか？

**Comment by Shogosuga** [comment]
@hiroalchem 
後者のvolumeとは、三方向全てで間違えてミトコンである（三方向からの推論値が255）であるpixelのvolumeであるという認識でよろしいでしょうか？

**Comment by hiroalchem** [comment]
そうです！

**Comment by Shogosuga** [comment]
@hiroalchem 
でしたら、10万pixels 以下です！

**Comment by Shogosuga** [comment]
@hiroalchem 
4つ前のコメントに書いていただいた様式で問題ないので、お手隙の際に実装していただきたいです。宜しくお願いします！

**Comment by hiroalchem** [comment]
@Shogosuga すみません、
>推論結果の2値化前の値の画像をxxx_raw
これってどういう形式で置いてもらえる予定でしょうか？
また、今ってミトコンドリアのラベルつけてる画像についてはERはラベルしてないって理解で良いでしょうか？

**Comment by Shogosuga** [comment]
@hiroalchem 
> これってどういう形式で置いてもらえる予定でしょうか？

8bit-grayscaleの画像をファイルに置くのはいかがでしょうか？

> また、今ってミトコンドリアのラベルつけてる画像についてはERはラベルしてないって理解で良いでしょうか？

はい。ERのラベルはついてないです。

**Comment by hiroalchem** [comment]
@Shogosuga feature/active_learning試してみていただけますか？？

**Comment by Shogosuga** [comment]
@hiroalchem 
ありがとうございます！今から使ってみます！

**Comment by Shogosuga** [comment]
@hiroalchem 
napariの立ち上げはlauncher_simple.pyからでよろしいでしょうか？

**Comment by Shogosuga** [comment]
@hiroalchem こちら、機能をdevelopにマージしたため、closeします。
